Repository ColonialMarines-Mirror/ColonialMarines-2018, pull requests merged in 2018-11, with the labels that each got.

#602 Sandbag Filling QoL
  code/game/objects/items/stacks/sandbags.dm
  code/game/objects/items/tools/shovel_tools.dm
Labels: QoL

#594 Further pill changes, have a medical candy.
  ColonialMarinesALPHA.dme
  code/datums/supplypacks.dm
  code/game/gamemodes/colonialmarines/whiskey_outpost.dm
  code/game/jobs/access.dm
  code/game/machinery/vending/marine_vending.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/game/objects/items/contraband.dm
  code/game/objects/items/devices/portable_vendor.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  maps/Z.03.USS_Almayer.dmm
  maps/backup/Z.03.USS_Almayer.dmm
Labels: Approved Conceptually, Code Improvement, Fix

#596 M41A MK2: Burst Fire Delay Reduced By 0.05 Seconds
  code/controllers/settings/combat_defines.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  config/example/combat_defines.txt
Labels: Balance/Rebalance, Test Merge Candidate

#598 Admin: Mentor SM fix, Further separation of ahelps and mhelps, Better note timestamps, Shorter log download cooldown, Admins can permaban, Randomized new humans
  code/__HELPERS/files.dm
  code/__HELPERS/global_lists.dm
  code/modules/admin/NewBan.dm
  code/modules/admin/admin_messages.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/create_mob.dm
  code/modules/admin/player_notes.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/client procs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/logout.dm
  code/modules/mob/mob_transformation_simple.dm
Labels: Administration

#611 Fixes infinite looping animation of Req vendor
  icons/obj/machines/vending.dmi
Labels: Fix

#560 Decapitate Decapitated
  code/modules/organs/limbs.dm
Labels: Tweak

#581 Rocket Tweak
  code/controllers/settings/combat_defines.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  code/modules/vehicles/cm_armored.dm
  code/modules/vehicles/hardpoints.dm
  config/example/combat_defines.txt
Labels: Balance/Rebalance

#599 Removes targetting mode
  code/_onclick/click.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/monkey.dm
  code/_onclick/hud/robot.dm
  code/_onclick/hud/screen_objects.dm
  code/modules/projectiles/targeting.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
Labels: Approved Conceptually

#619 Adds Shotgun Shell Pouches to Requisition.
  code/game/gamemodes/cm_initialize.dm
  code/game/machinery/vending/marine_vending.dm
Labels: Approved Conceptually, Balance/Rebalance

#603 Distress beacon rework
  code/datums/emergency_calls/emergency_call.dm
  code/game/machinery/computer/communications.dm
  code/modules/admin/topic.dm
Labels: Approved Conceptually, Balance/Rebalance, Tweak

#618 Plasma Cutter Minor Bug Fixes + Plasma Cutter Cuts Structure/Machines By Default
  code/game/machinery/doors/shutters.dm
  code/game/machinery/machinery.dm
  code/game/objects/items/tools/mining_tools.dm
  code/game/objects/structures.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
Labels: Approved Conceptually, Fix

#465 Fire Rebalance: Disco Inferno
  code/__DEFINES/conflict.dm
  code/game/objects/items.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/tools/extinguisher.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  icons/Marine/marine-weapons.dmi
Labels: Approved Conceptually, Balance/Rebalance

#615 Adding in Valmoric's lobby screens, except properly this time
  code/game/turfs/walls/wall_types.dm
  icons/misc/title.dmi
Labels: Approved Conceptually, Sprites

#614 New Medic Item: Medevac Beacon
  code/__DEFINES/objects.dm
  code/datums/supplypacks.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  icons/obj/items/devices.dmi
Labels: Approved Conceptually, Balance/Rebalance, Feature

#572 Facehugger/Carrier Tweak
  code/modules/mob/living/carbon/xenomorph/Castes/Carrier.dm
  code/modules/mob/living/carbon/xenomorph/Facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/XenoUpgrade.dm
Labels: Balance/Rebalance

#570 Further Necessary Defender Fortify/Crest Defense Buffs After Actually Playing One
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Defender.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoUpgrade.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Balance/Rebalance

#612 2 Walls 2 Furious (Bay walls round 2)
  icons/obj/structures/window_frames.dmi
  icons/obj/structures/windows.dmi
  icons/turf/walls.dmi
Labels: Approved Conceptually, Sprites

#626 FAcehugger delay tweak HOTFIX MERGE NOW
  code/modules/mob/living/carbon/xenomorph/Facehuggers.dm
Labels: Bug, Fix

#550 Crusher Rework
  code/controllers/settings/combat_defines.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Crusher.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  config/example/combat_defines.txt
  icons/mob/actions.dmi
Labels: Balance/Rebalance

#595 Husking Removed
  code/controllers/settings/game_options.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  config/config.txt
Labels: Balance/Rebalance

#360 Tackle Rework for Xenos
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life/handle_shock.dm
  code/modules/mob/living/carbon/human/life/handle_status_effects.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Boiler.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Carrier.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Crusher.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Defender.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Drone.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Hivelord.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Hunter.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Praetorian.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Predalien.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Ravager.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Runner.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Sentinel.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Spitter.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Warrior.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Xenoborg.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/XenoUpgrade.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
Labels: Approved Conceptually, Balance/Rebalance

#569 Overwatch and Laser Target reworks
  code/__DEFINES/misc.dm
  code/__HELPERS/global_lists.dm
  code/game/jobs/job/squads.dm
  code/game/machinery/camera/presets.dm
  code/game/machinery/cryopod.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/items/devices/binoculars.dm
  code/modules/almayer/machinery.dm
  code/modules/cm_marines/orbital_cannon.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/obj/machines/computer.dmi
  maps/Z.03.USS_Almayer.dmm
Labels: Tested

#479 Storage Tweak/Backpack Buff
  code/datums/supplypacks.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/gamemodes/colonialmarines/halloween2016.dm
  code/game/machinery/vending/marine_vending.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/modules/admin/verbs/select_equipment.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/cm_marines/smartgun_mount.dm
  icons/obj/items/storage/storage.dmi
Labels: Balance/Rebalance

#617 Xeno Queen rolling rework + monkey rebalance.
  code/game/gamemodes/cm_initialize.dm
  code/game/gamemodes/colonialmarines/colonialmarines.dm
Labels: Approved Conceptually, Balance/Rebalance

#631 New Carrier Ability: Spawn Hugger
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Carrier.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  icons/mob/actions.dmi
Labels: Approved Conceptually, Balance/Rebalance

#576 Sentry Upgrades + Minisentries - READY FOR TEST MERGE
  code/__DEFINES/objects.dm
  code/__HELPERS/unsorted.dm
  code/datums/supplypacks.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  icons/Marine/miniturret.dmi
  icons/Marine/turret.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/obj/items/ammo.dmi
  nano/templates/minisentry.tmpl
  nano/templates/sentry.tmpl
Labels: Approved Conceptually, Balance/Rebalance

#621 Hunter Rework: Stealthy Boi
  code/ATMOSPHERICS/atmospherics.dm
  code/__DEFINES/mobs.dm
  code/_onclick/ventcrawl.dm
  code/game/gamemodes/cm_process.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Hunter.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/XenoUpgrade.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  icons/Xeno/1x1_Xenos.dmi
Labels: Balance/Rebalance, Tweak

#610 Ravager Rework - Angry Red Dinosaur
  code/__DEFINES/mobs.dm
  code/datums/round_statistics.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Ravager.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/XenoUpgrade.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  icons/mob/actions.dmi
Labels: Balance/Rebalance, Feature

#643 Adding lobby screens based on Valmoric's work
  icons/misc/title.dmi
Labels: Sprites

#639 LV resize and cleanup
  maps/Z.01.LV624.dmm
Labels: Mapping

#649 Explosive Pouch Tweak: Now Holds Rockets
  code/game/objects/items/storage/pouch.dm
Labels: Balance/Rebalance

#650 HOTFIX: Improving Carrier Facehugging/Spawning
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Carrier.dm
  code/modules/mob/living/carbon/xenomorph/Facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
Labels: Fix

#648 Ravager Rework Tweaks
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Ravager.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Balance/Rebalance, Tweak

#629 Walls 3: Shuttle Drift
  icons/turf/ert_shuttle.dmi
Labels: Sprites

#655 Minor Sentry Tweak for Coordinate Reporting
  code/modules/cm_marines/equipment/sentries.dm
Labels: Fix

#636 Fiddling around with my good share of runtimes.
  code/datums/mind.dm
  code/game/objects/items/storage/fancy.dm
  code/modules/cm_marines/marines_consoles.dm
  code/modules/reagents/chemistry_reagents/alcohol.dm
  code/modules/reagents/chemistry_reagents/drink.dm
  code/modules/reagents/chemistry_reagents/food.dm
Labels: Fix

#635 "That's a big prison wall." "4 YOU!" (prison walls/windows/frames)
  icons/obj/structures/window_frames.dmi
  icons/obj/structures/windows.dmi
  icons/turf/walls/prison.dmi
Labels: Sprites

#622 Floodlight upgrade
  code/game/machinery/groundmap_geothermal.dm
  icons/obj/machines/floodlight.dmi
  icons/turf/ground_map.dmi
Labels: Approved Conceptually, Sprites

#640 adds AntiAir cannon firing sprite
  code/modules/cm_marines/orbital_cannon.dm
  icons/obj/machines/artillery.dmi
Labels: Sprites

#658 Re-adding Gorg's walls/windows/frames after receiving permission to use them
  icons/obj/structures/gorg_window_frames.dmi
  icons/obj/structures/gorg_windows.dmi
  icons/turf/gorg_almayer.dmi
  icons/turf/walls/gorg_prison.dmi
Labels: Approved Conceptually, Sprites

#663 Walls 5: Nights at Research (new research wall containment sprites)
  icons/turf/almayer.dmi
Labels: Sprites

#620 Bipods made more mobile, allows use of window frames as support
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
Labels: Balance/Rebalance

#659 Second Wind Fix + Speed Nerf
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/XenoUpgrade.dm
Labels: Fix

#660 Self-Splints No Longer RNG; Benefit From Med Skill
  code/modules/organs/limbs.dm
Labels: Approved Conceptually, Balance/Rebalance, QoL

#661 Fixing a Bug With Crest Toss
  code/game/atoms_movable.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
Labels: Fix

#662 Botany one liner change.
  code/modules/hydroponics/hydro_tray.dm
Labels: Fix

#630 New sentry sprite (sprites only no code)
  icons/Marine/new_sentry.dmi
  icons/Marine/new_sentry_alt.dmi
Labels: Sprites

#677 Fixes almayer turf sprites
  code/game/turfs/walls/wall_types.dm
  icons/turf/almayer.dmi
  icons/turf/almayerwalls.dmi
Labels: Fix

#683 Further Ravager Speed Nerfs
  code/modules/mob/living/carbon/xenomorph/Castes/Ravager.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/XenoUpgrade.dm
Labels: Balance/Rebalance, Tweak

#675 Adds barricade melee blocking from xenos.
  code/__DEFINES/equipment.dm
  code/_onclick/adjacent.dm
  code/_onclick/xeno.dm
  code/game/objects/structures.dm
  code/game/objects/structures/barricade.dm
Labels: Approved Conceptually, Feature

#646 LTB Cannon Now Has 0.5 Second Delay
  code/modules/projectiles/updated_projectiles/projectile.dm
  code/modules/vehicles/hardpoints.dm
Labels: Balance/Rebalance

#667 New wood walls/windows/window frames
  icons/obj/structures/window_frames.dmi
  icons/obj/structures/windows.dmi
  icons/turf/wood.dmi
Labels: Sprites

#678 Adds MP channel to command headsets. All channels start enabled.
  code/game/objects/items/devices/radio/encryptionkey.dm
Labels: Approved Conceptually, Tweak

#666 Mentor changes
  code/__HELPERS/game.dm
  code/game/jobs/job/upp.dm
  code/game/verbs/ooc.dm
  code/game/verbs/who.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminsay.dm
  code/modules/admin/verbs/deadsay.dm
  code/modules/admin/verbs/pray.dm
  code/modules/mob/emote.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/say.dm
Labels: Administration

#656 Adds an admin spawned uniform
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/uniform_0.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Approved Conceptually, Sprites

#668 Removes ageism and discrimination.
  ColonialMarinesALPHA.dme
  code/game/gamemodes/colonialmarines/whiskey_outpost.dm
  code/game/jobs/access.dm
  code/game/jobs/job/other.dm
  code/game/jobs/job/shipside.dm
  code/game/jobs/job/squads.dm
  code/game/jobs/role_authority.dm
  code/game/machinery/bots/medbot.dm
  code/game/machinery/vending/vending.dm
  code/modules/economy/Job_Departments.dm
  code/modules/economy/economy_misc.dm
Labels: Fix

#691 Ammo HUD Sprites
  icons/mob/ammoHUD.dmi
Labels: Sprites

#672 Prevents Warriors and Defenders from ventcrawling
  code/modules/mob/living/carbon/xenomorph/Castes/Defender.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Warrior.dm
  code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
Labels: Balance/Rebalance, Tweak

#680 Adds rebreathers to marine vendors.
  code/game/gamemodes/cm_initialize.dm
  code/game/machinery/vending/marine_vending.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  config/admins.txt
Labels: Approved Conceptually, Tweak

#681 Add some access to Maintenance Technician
  code/game/jobs/job/shipside.dm
Labels: Balance/Rebalance, Tweak

#689 Pill machine buffer 120 to 240
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Approved Conceptually, Tweak

#692 Makes locally joined clients admin automaticaly
  ColonialMarinesALPHA.dme
  code/__DEFINES/flags.dm
  code/modules/client/client procs.dm
  code/modules/clothing/suits/marine_armor.dm
Labels: Feature

#690 Better information dogtags examine.
  code/game/objects/items/cards_ids.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: QoL

#703 Replaces return 0/1 in mob_helpers with FALSE/TRUE
  code/modules/mob/mob_helpers.dm
Labels: Code Improvement

#700 Scout Tweak
  code/__DEFINES/objects.dm
  code/game/objects/items/devices/motion_detector.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/cm_marines/equipment/weapons.dm
  icons/Marine/marine-items.dmi
Labels: Balance/Rebalance, Tweak

#671 B18 Overhaul: Automedical System
  code/__DEFINES/objects.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/objs.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/suits/suit_procs.dm
  code/modules/cm_marines/equipment/weapons.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/organs/limbs.dm
Labels: Balance/Rebalance

#699 Gives the Flechettes a big ammo box, and adds them to the req ammo vendor and ASRS supply list
  code/datums/supplypacks.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/machinery/vending/marine_vending.dm
  code/modules/projectiles/updated_projectiles/ammunition.dm
  icons/obj/items/ammo.dmi
Labels: Approved Conceptually, Feature, Sprites

#684 Explosive Pouch Added to Marine/SL/Spec Vendors
  code/game/machinery/vending/new_marine_vendors.dm
Labels: Approved Conceptually, Tweak

#702 Ravager Now Has a Rage-O-Meter in its Stat Tab Also Rage GainZ From Damage Procs Limited
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Ravager.dm
  code/modules/mob/living/carbon/xenomorph/XenoUpgrade.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
Labels: Balance/Rebalance, QoL

#707 Defender Plasma Costs Doubled
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Balance/Rebalance

#695 Xeno datums
  ColonialMarinesALPHA.dme
  code/__DEFINES/mobs.dm
  code/__HELPERS/global_lists.dm
  code/datums/mob_hud.dm
  code/game/gamemodes/colonialmarines/whiskey_outpost.dm
  code/game/machinery/door_control.dm
  code/game/machinery/groundmap_geothermal.dm
  code/game/machinery/vending/vending.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/modules/cm_aliens/Ovipositor.dm
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/cm_marines/smartgun_mount.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Boiler.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Carrier.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Crusher.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Defender.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Drone.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Hivelord.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Hunter.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Larva.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Praetorian.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Predalien.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Ravager.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Runner.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Sentinel.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Spitter.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Warrior.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Xenoborg.dm
  code/modules/mob/living/carbon/xenomorph/Evolution.dm
  code/modules/mob/living/carbon/xenomorph/Facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoAttacks.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/XenoUpgrade.dm
  code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/egg_item.dm
  code/modules/mob/living/carbon/xenomorph/emote.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  code/modules/shuttles/shuttle_console.dm
  code/modules/vehicles/cm_armored.dm
Labels: Code Improvement, Refactor

#382 Neurotoxin Rework
  code/game/objects/effects/aliens.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/carbon_helpers.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Boiler.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Praetorian.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Sentinel.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Spitter.dm
  code/modules/mob/living/carbon/xenomorph/Evolution.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoUpgrade.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  code/modules/reagents/chemistry_reagents/other.dm
Labels: Balance/Rebalance, Test Merge Candidate

#708 MedVac Bed/Beacon Improvements
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: QoL

#705 Edgy armor [Sprites only]
  icons/mob/feet.dmi
  icons/mob/head_1.dmi
  icons/mob/suit_1.dmi
  icons/mob/uniform_0.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#674 Fire Tweaks
  code/game/objects/items/explosives/grenades/marines.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/living_defines.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
Labels: Balance/Rebalance

#709 Explosive pouch cap increased to 4
  code/game/objects/items/storage/pouch.dm
Labels: Balance/Rebalance

#717 Xeno datums
  ColonialMarinesALPHA.dme
  code/__DEFINES/mobs.dm
  code/__HELPERS/global_lists.dm
  code/datums/mob_hud.dm
  code/game/gamemodes/colonialmarines/whiskey_outpost.dm
  code/game/machinery/door_control.dm
  code/game/machinery/groundmap_geothermal.dm
  code/game/machinery/vending/vending.dm
  code/game/mecha/mecha.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/modules/cm_aliens/Ovipositor.dm
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/cm_marines/smartgun_mount.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Boiler.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Carrier.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Crusher.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Defender.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Drone.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Hivelord.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Hunter.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Larva.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Praetorian.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Predalien.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Ravager.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Runner.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Sentinel.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Spitter.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Warrior.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Xenoborg.dm
  code/modules/mob/living/carbon/xenomorph/Evolution.dm
  code/modules/mob/living/carbon/xenomorph/Facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoAttacks.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/XenoUpgrade.dm
  code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/egg_item.dm
  code/modules/mob/living/carbon/xenomorph/emote.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  code/modules/shuttles/shuttle_console.dm
  code/modules/vehicles/cm_armored.dm
Labels: Refactor

#710 M4A3 Mag Boxes
  code/datums/supplypacks.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/machinery/vending/marine_vending.dm
  code/modules/projectiles/updated_projectiles/ammunition.dm
  icons/obj/items/ammo.dmi
Labels: Sprites

#679 More detailed medical hud + dead body defibbable examine
  code/controllers/settings/configuration.dm
  code/datums/mob_hud.dm
  code/game/objects/items/devices/defibrillator.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Embryo.dm
  icons/mob/hud.dmi
Labels: QoL

#455 New Marine Item: Detpack - READY FOR REVIEW + POSSIBLE TEST MERGE
  ColonialMarinesALPHA.dme
  code/__DEFINES/conflict.dm
  code/__HELPERS/global_lists.dm
  code/_onclick/adjacent.dm
  code/controllers/processes/second.dm
  code/datums/supplypacks.dm
  code/game/atoms_movable.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/game/objects/items/devices/radio/detpack.dm
  code/game/objects/items/explosives/plastique.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/cm_marines/equipment/weapons.dm
  icons/obj/det.dmi
  icons/obj/items/assemblies.dmi
Labels: Approved Conceptually, Balance/Rebalance

#682 Sprites for bugs / Cimex (barebones edition)
  icons/Cimex/1x1structures.dmi
  icons/Cimex/2x2structures.dmi
  icons/Cimex/3x3structures.dmi
  icons/Cimex/basicunits.dmi
  icons/Cimex/playerunits.dmi
Labels: Feature, Sprites

#715 Adds carlarc's M240T sprites
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/gun.dmi
Labels: Approved Conceptually, Sprites

#701 QoL: Basic Uniform Consolidated Into One Button
  code/game/machinery/vending/new_marine_vendors.dm
Labels: QoL

#669 Removes specialist gear ID locks and reworks the spec skill for non-specialists.
  code/__DEFINES/conflict.dm
  code/__DEFINES/skills.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/cm_marines/equipment/weapons.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Approved Conceptually, Tweak

#693 Motion Detector Auto-Deactivates If User Dead
  code/game/objects/items/devices/motion_detector.dm
Labels: Approved Conceptually, Tweak

#726 Fixes layering of shutters when open
  code/game/machinery/doors/shutters.dm
  maps/Z.03.USS_Almayer.dmm
Labels: Fix, Mapping

#732 Hotfixes a compile error.
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
Labels: Fix

#716 Hopeful Sentry Fix to Rare Bug
  code/modules/cm_marines/equipment/sentries.dm
Labels: Fix

#735 Fixes a mistake I made way back during the first Almayer remap
  code/game/objects/structures/crates_lockers/closets/fitness.dm
Labels: Fix

#740 M3 Armor Variants and Marine Vendor Tweak
  code/game/jobs/job/shipside.dm
  code/game/machinery/vending/marine_vending.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/game/machinery/vending/vending.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/suits/storage.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
Labels: Balance/Rebalance

#738 Update r_human.dmi
  icons/mob/human_races/r_human.dmi
Labels: Approved Conceptually, Sprites

#719 Uncomments the thermite reaction
  code/modules/reagents/chemistry_reactions/other.dm
Labels: Balance/Rebalance

#736 Changes Claymore Description
  code/game/objects/items/weapons/blades.dm
Labels: Grammar and Formatting
