Repository ColonialMarines-Mirror/ColonialMarines-2018, pull requests merged in 2018-10, with the labels that each got.

#406 Delets all donor items sprites and related files
  ColonialMarinesALPHA.dme
  code/game/machinery/cryopod.dm
  code/modules/cm_marines/Donor_Items.dm
  icons/DONOR/BOOT.dmi
  icons/DONOR/HEAD.dmi
  icons/DONOR/MASKS.dmi
  icons/DONOR/MISC.dmi
  icons/DONOR/RainbowCoat.dmi
  icons/DONOR/SUITS.dmi
  icons/DONOR/Sanctum Uniforms.dmi
  icons/DONOR/UNIFORM.dmi
  icons/mob/feet.dmi
  icons/mob/head_0.dmi
  icons/mob/mask.dmi
  icons/mob/suit_0.dmi
  icons/mob/uniform_0.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/items/items.dmi
Labels: Sprites

#399 Almayer Map Resize
  maps/Z.03.USS_Almayer.dmm
Labels: Mapping

#278 Nukes smartgun bullets doing more damage with IFF off
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#366 Xenos Can't Drag Corpses
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/xenomorph/Facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/mob.dm
Labels: Balance/Rebalance, Tweak

#334 Adds a marine vendor for PFCs
  code/game/machinery/vending/new_marine_vendors.dm
Labels: Balance/Rebalance

#394 SMG Fix
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
Labels: Balance/Rebalance, Test Merge Candidate

#420 More Titles III: Attack of the Meme
  code/game/turfs/walls/wall_types.dm
  icons/misc/title.dmi
Labels: Sprites

#400 Req vendors rebalance and cleanup.
  code/datums/supplypacks.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/machinery/vending/marine_vending.dm
Labels: Balance/Rebalance, Tweak

#395 Big Xeno Rebalance
  ColonialMarinesALPHA.dme
  code/__DEFINES/mobs.dm
  code/__DEFINES/mode.dm
  code/_onclick/xeno.dm
  code/datums/emergency_calls/xenos.dm
  code/datums/supplyexports.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/gamemodes/colonialmarines/colonialmarines.dm
  code/game/gamemodes/colonialmarines/whiskey_outpost.dm
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/cm_aliens/weeds.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Boiler.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Carrier.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Crusher.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Defender.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Drone.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Hivelord.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Hunter.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Praetorian.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Ravager.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Runner.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Sentinel.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Spitter.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Warrior.dm
  code/modules/mob/living/carbon/xenomorph/Embryo.dm
  code/modules/mob/living/carbon/xenomorph/Evolution.dm
  code/modules/mob/living/carbon/xenomorph/Facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/XenoUpgrade.dm
  code/modules/mob/living/carbon/xenomorph/XenoUpgrades.dm
  code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  icons/Xeno/1x1_Xenos.dmi
Labels: Balance/Rebalance

#427 Changed medivend sprite animation
  icons/obj/machines/vending.dmi
Labels: Sprites

#446 Partial change of almayer area sprites
  icons/turf/area_almayer.dmi
Labels: Sprites

#442 M37 Pump Lock and Notification
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
Labels: Approved Conceptually, Tweak

#440 Minor Attachments Rebalance
  code/controllers/settings/combat_defines.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
Labels: Balance/Rebalance

#441 Almayer Fixes and Adjustments
  maps/Z.03.USS_Almayer.dmm
Labels: Mapping

#461 Pump Shotgun Lock Feedback Fix
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
Labels: Approved Conceptually, Fix

#458 Fixes suit lamp displaying bug
  icons/obj/clothing/cm_suits.dmi
Labels: Sprites

#443 Further SMG Improvements
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
Labels: Balance/Rebalance, Test Merge Candidate

#473 No scout xeno left behind
  code/modules/shuttles/marine_ferry.dm
Labels: Approved Conceptually, Fix, Tested

#483 Dust Raider Sprite Swapover
  icons/mob/back.dmi
  icons/mob/belt.dmi
  icons/mob/head_1.dmi
  icons/mob/suit_1.dmi
  icons/mob/uniform_0.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/items/storage/storage.dmi
Labels: Sprites, Tested

#422 Set Respawn Timer admin verb.
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mob/mob_verbs.dm
Labels: Administration

#339 [100% tested] Ports multiple changes by goonstation to their process scheduler, These should cause a minor performance increase.
  code/controllers/ProcessScheduler/defines.dm
  code/controllers/ProcessScheduler/process.dm
  code/controllers/ProcessScheduler/processScheduler.dm
  code/controllers/ProcessScheduler/stubs.dm
  code/controllers/processes/world.dm
  code/game/objects/explosion_recursive.dm
  code/modules/admin/admin_verbs.dm
Labels: Code Improvement

#472 Replace Big Red CM turf sprites with TG turf sprites
  icons/turf/bigred.dmi
Labels: Approved Conceptually, Sprites, Tested

#435 Attack logs are no longer generated after roundend
  code/__DEFINES/__game.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
Labels: Administration

#491 Less racial discrimination.
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
Labels: Approved Conceptually, Tweak

#457 Vents bug fix
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/pipes.dm
  code/_onclick/ventcrawl.dm
Labels: Tested

#459 Return of the audible emote cooldown.
  code/modules/mob/living/carbon/human/emote.dm
Labels: Tested

#492 Some new sprites for the Autodoc and the Bioprinter.
  code/game/machinery/autodoc.dm
  code/game/machinery/bioprinter.dm
  icons/obj/machines/cryogenics.dmi
  icons/obj/surgery.dmi
Labels: Approved Conceptually, Sprites, Tested

#460 Fix duplicate constant issues.
  code/game/objects/structures/mineral_doors.dm
  code/global.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  code/modules/shuttles/shuttle_hangar.dm
Labels: Tested

#495 Adds in-game webmap button
  code/controllers/settings/configuration.dm
  config/config.txt
  interface/interface.dm
  interface/skin.dmf
Labels: Feature, Tested

#501 Fixes "Nanotrasen Vision Enhancing Shades"
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/human_status_procs.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/mob/living/living_helpers.dm
  code/modules/mob/mob_status_procs.dm
  code/modules/reagents/chemistry_reagents/medical.dm
Labels: Fix

#502 Armor Fixes
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/marine_armor.dm
Labels: Approved Conceptually, Fix

#372 Squad Leader Vendor/Essential Update
  code/game/machinery/vending/new_marine_vendors.dm
  code/game/objects/items/devices/motion_detector.dm
  code/game/objects/items/storage/pouch.dm
Labels: Balance/Rebalance, Test Merge Candidate

#503 Cigar Fix
  code/game/objects/items/tools/flame_tools.dm
  icons/mob/mask.dmi
  icons/obj/clothing/masks.dmi
Labels: Approved Conceptually, Fix, Sprites

#313 Plasma Cutter 2.0
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/__DEFINES/objects.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/game/objects/items.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/items/tools/mining_tools.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/window_frame.dm
  code/game/turfs/closed.dm
  code/game/turfs/walls/r_wall.dm
  code/game/turfs/walls/wall_types.dm
  code/game/turfs/walls/walls.dm
  code/modules/cm_aliens/XenoStructures.dm
  icons/mob/belt.dmi
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/obj/items/items.dmi
Labels: Approved Conceptually, Balance/Rebalance, Feature

#506 fixes/adds/ports mre/snacks/food and literal trash
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/storage/boxes.dm
  icons/obj/items/food.dmi
  icons/obj/items/trash.dmi
Labels: Approved Conceptually, Fix, Sprites

#426 Improved Sleeper - READY FOR MERGE
  code/game/machinery/Sleeper.dm
Labels: Approved Conceptually

#505 Space Jam score board replacement
  icons/obj/machines/scoreboard.dmi
Labels: Approved Conceptually, Sprites

#471 Fixes #148. Removes the "EORG" from lazyban.
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/debug.dm
Labels: Administration, Approved Conceptually

#428 New Runner Ability: Savage - NEEDS REVIEW
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Runner.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  icons/mob/actions.dmi
Labels: Approved Conceptually, Balance/Rebalance, Feature, Test Merge Candidate

#485 Brings centcom slightly up to date
  code/game/area/Space Station 13 areas.dm
  code/game/machinery/doors/shutters.dm
  code/modules/shuttles/shuttle_ert.dm
  config/admins.txt
  maps/Z.02.Admin_Level.dmm
Labels: Approved Conceptually, Mapping, Tested

#464 Nerf: Tactical Shotgun MK223
  code/controllers/settings/combat_defines.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/magazines/shotguns.dm
  config/combat_defines.txt
Labels: Balance/Rebalance

#508 Call me maybe (Replacing telecomms & tower sprites)
  icons/obj/machines/comm_tower.dmi
  icons/obj/stationobjs.dmi
Labels: Approved Conceptually, Sprites, WIP

#512 Melee Tweak
  code/game/objects/items/weapons/blades.dm
Labels: Balance/Rebalance

#513 Random Sprite Stuff
  code/modules/cm_marines/flare_gun.dm
  icons/Marine/SEASONS/xmas.dmi
  icons/Marine/flaregun.dmi
  icons/Seasonal/1x1_Xenos_XMAS.dmi
  icons/Seasonal/2x2_Xenos_XMAS.dmi
  icons/contain.dmi
  icons/misc/beach2.dmi
  icons/misc/fullscreen.gif
  icons/obj/apiary_bees_etc.dmi
  icons/obj/items/drinks.dmi
  icons/obj/items/items.dmi
  icons/obj/kitchen.dmi
  icons/obj/machines/chemical_machines.dmi
  icons/obj/machines/status_display.dmi
  icons/obj/objects.dmi
  icons/obj/pipes.dmi
  icons/obj/ship_engine.dmi
  icons/obj/status_display.dmi
  icons/obj/structures/crates.dmi
  icons/obj/structures/structures.dmi
  icons/obj/watercloset.dmi
  nano/images/uiMaskBackground.png
Labels: Sprites

#510 Attachment and Ammo Rebalance
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
Labels: Approved Conceptually, Balance/Rebalance

#421 Cryotube Fix/Improvement - READY FOR MERGE
  code/game/machinery/cryo.dm
  code/game/objects/items/reagent_containers/glass.dm
  code/modules/mob/living/carbon/human/life/handle_breath.dm
  code/modules/mob/living/carbon/human/life/handle_environment.dm
  code/modules/mob/living/carbon/human/life/handle_stasis_bag.dm
  maps/Z.02.Admin_Level.dmm
  maps/Z.03.USS_Almayer.dmm
  maps/backup/Z.03.USS_Almayer.dmm
  nano/templates/cryo.tmpl
Labels: Balance/Rebalance, Tweak

#432 Autodoc Improvement
  code/game/machinery/adv_med.dm
  code/game/machinery/autodoc.dm
  code/game/machinery/machinery.dm
Labels: Approved Conceptually, Tweak

#484 Headbutt + Tail Sweep Hotfix
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Approved Conceptually, Fix, Tested

#523 [HIGH PRIORITY] CRYO NAME CHANGE
  maps/Z.01.BigRed_v2.dmm
  maps/Z.01.Prison_Station_FOP.dmm
Labels: Fix, Priority: High

#517 Disables the meaningless intercept report on extended.
  code/game/gamemodes/extended/extended.dm
Labels: Approved Conceptually, Tweak

#515 Clutter, now with 100% more drab olive greens
  config/admins.txt
  icons/obj/structures/crates.dmi
Labels: Sprites

#482 Turns chat, github and patreon links into configs
  code/controllers/settings/configuration.dm
  code/game/world.dm
  code/modules/admin/verbs/adminhelp.dm
  config/config.txt
  config/example/config.txt
  interface/interface.dm
Labels: Tested

#522 Ice n' Elevators
  code/game/machinery/doors/multi_tile.dm
  code/modules/shuttles/marine_ferry.dm
  icons/obj/doors/4x1_elevator.dmi
  icons/obj/doors/4x1_elevator_access.dmi
  icons/obj/doors/icecolony.dmi
  maps/Z.01.Ice_Colony_v2.dmm
Labels: Fix, Mapping, Priority: High, Sprites

#518 Gives the M41A, M4A3, and M39 Extended mag sprites. Also updates the incendiary and AP mags for the M4A3
  code/modules/projectiles/updated_projectiles/magazines/pistols.dm
  code/modules/projectiles/updated_projectiles/magazines/rifles.dm
  code/modules/projectiles/updated_projectiles/magazines/smgs.dm
  icons/obj/items/ammo.dmi
Labels: Approved Conceptually, Sprites

#519 Balance Patch
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#529 Gives the M4A3 Hollow Point Mags Their Own Sprite
  code/modules/projectiles/updated_projectiles/magazines/pistols.dm
  icons/obj/items/ammo.dmi
Labels: Approved Conceptually, Sprites

#526 Medbay MarineMed Vendor/Smartfridge Access Granted
  code/game/machinery/kitchen/smartfridge.dm
  code/game/machinery/vending/marine_vending.dm
Labels: Balance/Rebalance

#504 Armor Reduction Fix - RNG Removal
  code/_onclick/other_mobs.dm
  code/modules/clothing/gloves/marine_gloves.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living_defense.dm
Labels: Balance/Rebalance

#537 OK Computer (replacing computer sprites)
  icons/obj/machines/computer.dmi
Labels: Approved Conceptually, Sprites

#488 Motion Detector Hotfix
  code/game/objects/items/devices/motion_detector.dm
Labels: Approved Conceptually, Do Not Merge, Fix, Test Merge Candidate

#511 Defender: Fortify/Defensive Stance Improvements
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#525 New Marine Vending Machine Sprite by Arachnidnexus
  code/game/machinery/vending/marine_vending.dm
  code/game/machinery/vending/new_marine_vendors.dm
  icons/obj/machines/vending.dmi
Labels: Approved Conceptually, Sprites

#531 Admin: Adds FLW to every JMP where applicable
  code/WorkInProgress/kilakk/fax.dm
  code/game/gamemodes/colonialmarines/whiskey_outpost.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/cryo.dm
  code/game/machinery/iv_drip.dm
  code/game/machinery/kitchen/gibber.dm
  code/game/objects/items/devices/aicard.dm
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/game/objects/items/explosives/grenades/chem_grenade.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/plastique.dm
  code/game/objects/items/implants/implanter.dm
  code/game/objects/items/reagent_containers/dropper.dm
  code/game/objects/items/reagent_containers/food/condiment.dm
  code/game/objects/items/reagent_containers/food/drinks.dm
  code/game/objects/items/reagent_containers/food/drinks/bottle.dm
  code/game/objects/items/reagent_containers/glass.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/reagent_containers/robodropper.dm
  code/game/objects/items/reagent_containers/syringes.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/tools/kitchen_tools.dm
  code/game/objects/items/tools/misc_tools.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/modules/admin/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/admin/verbs/adminsay.dm
  code/modules/admin/verbs/pray.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/cm_preds/smartdisc.dm
  code/modules/cm_preds/yaut_items.dm
  code/modules/hydroponics/grown_inedible.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/organs/limb_objects.dm
  code/modules/organs/organ_objects.dm
  code/modules/power/cable.dm
  code/modules/power/singularity/emitter.dm
  code/modules/power/singularity/particle_accelerator/particle_control.dm
  code/modules/power/smes_construction.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/guns/misc.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  code/modules/recycling/disposal.dm
  code/modules/scripting/IDE.dm
Labels: Administration, Approved Conceptually

#532 Admin: Proper suicide logging
  code/modules/projectiles/updated_projectiles/gun_system.dm
Labels: Administration

#539 Admin: Proper table slam, window slam, swirlie, toilet slam logging
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/watercloset.dm
  code/game/objects/structures/window.dm
Labels: Administration, Approved Conceptually

#545 buying HE grenades gives you HE grenades
  code/game/machinery/vending/new_marine_vendors.dm
Labels: Fix

#548 UPP rations fix.
  code/game/objects/items/reagent_containers/food/snacks.dm
Labels: Approved Conceptually, Fix

#554 Dust Raider Weaponry
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/belt.dmi
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_0.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/items/gun.dmi
Labels: Approved Conceptually, Sprites

#520 Pump Notification Spam Fix
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
Labels: Fix

#549 Fixes #542
  code/modules/projectiles/updated_projectiles/gun_system.dm
Labels: Approved Conceptually, Fix, Grammar and Formatting

#547 Gives admins their newscaster back
  code/modules/admin/admin_verbs.dm
Labels: Administration, Approved Conceptually

#544 Makes Requisitions windows more resistant
  code/game/objects/structures/window.dm
Labels: Approved Conceptually, Tweak

#534 Fixed Cryo and Autoinjector Bug
  code/game/machinery/bots/medbot.dm
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/borghydro.dm
  code/game/objects/items/reagent_containers/glass.dm
  code/modules/reagents/chemistry_reactions/medical.dm
  code/modules/reagents/chemistry_reagents/medical.dm
Labels: Fix

#538 Plasma Cutter Formatting Improvement
  code/ATMOSPHERICS/components/unary/vent_pump.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/__DEFINES/objects.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/tools/mining_tools.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_frame.dm
  code/game/turfs/closed.dm
  code/game/turfs/walls/r_wall.dm
  code/game/turfs/walls/wall_types.dm
  code/game/turfs/walls/walls.dm
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/cm_aliens/weeds.dm
Labels: Approved Conceptually, Balance/Rebalance, Feature

#562 Admin: Several fixes relating to previous PRs
  code/game/verbs/suicide.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  code/modules/recycling/disposal.dm
Labels: Administration, Fix

#551 Admin: Allows players to view their own notes (OOC > View Admin Remarks)
  code/modules/admin/admin.dm
  code/modules/admin/player_notes.dm
  code/modules/admin/topic.dm
  code/modules/mob/mob_verbs.dm
Labels: Administration, Approved Conceptually

#566 Actually fixes rogue autoinjectors
  ColonialMarinesALPHA.dme
  code/WorkInProgress/Cael_Aislinn/Jungle/jungle_plants.dm
  code/WorkInProgress/Cib/MedicalSideEffects.dm
  code/__DEFINES/objects.dm
  code/datums/supplypacks.dm
  code/game/gamemodes/colonialmarines/halloween2016.dm
  code/game/gamemodes/colonialmarines/whiskey_outpost.dm
  code/game/jobs/job/wy_pmc.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/autodoc.dm
  code/game/machinery/bots/medbot.dm
  code/game/machinery/machinery.dm
  code/game/machinery/vending/marine_vending.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/game/machinery/vending/vending_types.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/borghydro.dm
  code/game/objects/items/reagent_containers/food/drinks/bottle/robot.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/reagent_containers/glass/bottle.dm
  code/game/objects/items/reagent_containers/glass/bottle/robot.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/reagent_containers/syringes.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/genetics/side_effects.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/Chemistry-Readme.dm
  code/modules/reagents/chemistry_reactions/food_drink.dm
  code/modules/reagents/chemistry_reactions/medical.dm
  code/modules/reagents/chemistry_reactions/other.dm
  code/modules/reagents/chemistry_reagents/medical.dm
  code/modules/reagents/chemistry_reagents/toxin.dm
  maps/Z.01.LV624.dmm
  maps/backup/Z.01.LV624.dmm
Labels: Fix

#536 Fixes a runtime error and cleans the code a little in medical_tools.dm
  code/game/mecha/equipment/tools/medical_tools.dm
Labels: Tested

#563 Fixes Computer Sprite Issue
  code/game/machinery/computer/station_alert.dm
  icons/obj/machines/computer.dmi
Labels: Fix, Sprites

#564 Warrior Punch Rework
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/organs/limbs.dm
Labels: Approved Conceptually, Balance/Rebalance

#552 Every observer now has persistent HUDs defined by the client preferences
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Approved Conceptually, Fix

#573 Hotkeys for selecting body parts
  code/modules/mob/mob_helpers.dm
  interface/skin.dmf
Labels: Approved Conceptually, QoL

#561 Tank Bumping
  code/modules/vehicles/cm_armored.dm
Labels: Balance/Rebalance, Fix, Tweak

#500 Xeno healing rework and fixes
  code/_onclick/ventcrawl.dm
  code/game/atoms_movable.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/implants/implantneurostim.dm
  code/game/objects/items/tanks/jetpack.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Boiler.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Carrier.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Predalien.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Ravager.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Warrior.dm
  code/modules/mob/living/carbon/xenomorph/Facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/mob/living/silicon/robot/analyzer.dm
  code/modules/reagents/chemistry_reagents/medical.dm
Labels: Tested

#559 Motion Detector Improvement
  code/game/objects/items/devices/motion_detector.dm
  icons/Marine/marine-items.dmi
Labels: Approved Conceptually, Tweak

#567 Faulty code fixing.
  code/modules/mob/living/brain/life.dm
  code/modules/mob/living/carbon/hellhound/life.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#577 More formatting fixes
  code/__DEFINES/objects.dm
  code/game/objects/items/tools/mining_tools.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/cm_aliens/weeds.dm
Labels: Tweak

#578 Gives the Sniper spec's flak and Incen mags their own sprites
  code/modules/projectiles/updated_projectiles/magazines/specialist.dm
  icons/obj/items/ammo.dmi
Labels: Approved Conceptually, Sprites

#592 Santizes the Dropship
  code/modules/surgery/surgery.dm
Labels: Balance/Rebalance

#593 Small adjustments to Nice
  maps/Z.01.Ice_Colony_v2.dmm
Labels: Mapping

#583 New admin test-only item: XenoMate HUD
  code/modules/clothing/glasses/hud.dm
  icons/mob/eyes.dmi
Labels: Approved Conceptually, Feature, Sprites

#497 Replacing Almayer walls with Bay walls
  icons/obj/structures/window_frames.dmi
  icons/obj/structures/windows.dmi
  icons/turf/almayer.dmi
Labels: Sprites, Tested

#588 Motion Detector Now Properly Differentiates Unrevivables
  code/game/objects/items/devices/motion_detector.dm
Labels: Fix

#582 Portable Generator Improvement
  code/modules/power/port_gen.dm
Labels: Balance/Rebalance

#601 Moves damage reduction from warding_aura from apply_damage to bullet_act
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
Labels: Approved Conceptually, Balance/Rebalance, Code Improvement

#530 Ladder bug fix.
  code/_onclick/hud/fullscreen.dm
  code/game/objects/structures/ladders.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
Labels: Tested

#584 Expanded Number of Marines That Can Use Remote Dropship Controls
  code/game/jobs/job/command.dm
  code/game/jobs/job/logistics.dm
  code/game/machinery/computer/communications.dm
  code/modules/shuttles/shuttle_console.dm
Labels: Balance/Rebalance
