Repository ColonialMarines-Mirror/ColonialMarines-2018, pull requests merged in 2018-09, with the labels that each got.

#159 Light me up inside (Adds CAS lighting flares)
  code/modules/cm_marines/dropship_ammo.dm
  icons/Marine/almayer_props.dmi
  maps/Z.03.USS_Almayer.dmm
Labels: Feature, Test Merge Candidate

#234 Tank Update
  ColonialMarinesALPHA.dme
  code/datums/skills.dm
  code/modules/vehicles/cm_armored.dm
  code/modules/vehicles/hardpoints.dm
  code/modules/vehicles/tankvendor.dm
  config/admins.txt
Labels: Balance/Rebalance, Feature, Fix, Test Merge Candidate

#193 Requisition windows are no longer strong enough to sustain a point-blank hit by a Tsar Bomba.
  code/game/objects/structures/window.dm
  code/modules/shuttles/marine_ferry.dm
Labels: Balance/Rebalance, Test Merge Candidate

#197 Selling xeno corspes feature
  ColonialMarinesALPHA.dme
  code/datums/supplyexports.dm
  code/game/supplyshuttle.dm
  code/modules/vehicles/powerloader.dm
Labels: Balance/Rebalance, Test Merge Candidate

#253 Reduces some of the roundstart pain for the PO, they now have more powerloader training.
  code/datums/skills.dm
Labels: Tweak

#199 Increases gestation speed when nested Tweak
  code/modules/mob/living/carbon/xenomorph/Embryo.dm
Labels: Balance/Rebalance, Test Merge Candidate

#105 Makes everything tg: Hotkeys & buttons edition
  interface/interface.dm
  interface/skin.dmf
Labels: Test Merge Candidate

#245 Med Scanner Improvement - Cont of #179
  code/game/objects/items/devices/scanners.dm
Labels: Balance/Rebalance, Test Merge Candidate, Tweak

#252 [HONK]Adds the Clown Survivor
  code/datums/skills.dm
  code/game/gamemodes/cm_initialize.dm
  code/modules/clothing/masks/gasmask.dm
Labels: Feature, Test Merge Candidate

#243 Remember kids, don't drink bleach or spray it on open wounds
  code/modules/reagents/chemistry_reagents/medical.dm
Labels: Test Merge Candidate, Tweak

#279 Hivemind now logs to players
  code/__DEFINES/logging.dm
  code/game/atoms.dm
  code/modules/mob/living/carbon/human/whisper.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
  config/admins.txt
Labels: Administration, Test Merge Candidate

#280 Tank Update Fix
  code/modules/vehicles/cm_armored.dm
Labels: Test Merge Candidate, bug

#285 Queen locator shows Hive Status when clicked
  code/_onclick/hud/screen_objects.dm
Labels: Test Merge Candidate

#238 Very very slightly optimizes can_see, it no longer runs one more time then needed.
  code/__HELPERS/unsorted.dm
Labels: Code Improvement

#287 Updated Med HUD So It Ignores Ghostless Bodies
  code/datums/mob_hud.dm
Labels: Fix

#283 You can now fully deconstruct girders. Fixes #184
  code/game/objects/structures/girders.dm
Labels: Fix

#284 No more anti-tank racks/showcases.
  code/modules/vehicles/cm_armored.dm
Labels: Fix

#281 The flamer now burns away vines.
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
Labels: Tweak

#241 Fixes robots and (ghost)drones autolathe bugs and exploits
  code/game/machinery/autolathe.dm
  code/game/objects/items/circuitboards/robot_modules.dm
Labels: Fix

#275 ADDED SHIT, REMOVED SHIT: ALMAYER EDITION
  maps/Z.03.USS_Almayer.dmm
Labels: Balance/Rebalance

#210 Follow humans now only shows living, non-SSD humans.
  code/__HELPERS/unsorted.dm
  code/modules/mob/dead/observer/observer.dm
Labels: bug

#321 Puts Supply Pads on Layer 2, fixing z-fight issues.
  code/modules/cm_marines/overwatch.dm
Labels: Fix

#186 Ports /tg/ ghost Player Panel fix and cleans up the Pred button
  code/datums/mind.dm
  code/modules/admin/topic.dm
  code/modules/mob/mob_transformation_simple.dm
Labels: Fix, Test Merge Candidate

#217 Ports in /tg/ vending.dmi, additonal re-spriting.
  code/game/machinery/kitchen/smartfridge.dm
  code/game/machinery/vending/marine_vending.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/game/machinery/vending/vending.dm
  icons/obj/machines/vending.dmi
Labels: Sprites

#347 Correcting Liaison typos : Attempt 2
  code/game/area/almayer.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/machinery/doors/airlock_types.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  maps/Z.03.USS_Almayer.dmm
Labels: Grammar and Formatting, Mapping

#341 flamers and boiler spray now reset their values on already affected turfs...
  code/game/objects/items/explosives/grenades/marines.dm
  code/modules/cm_marines/dropship_ammo.dm
  code/modules/cm_marines/orbital_cannon.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Boiler.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Ravager.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/reagents/chemistry_reactions/other.dm
Labels: Tweak

#348 Enables squad marine access to general chat
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
Labels: Tweak

#343 More consistency and exploit patches for the autolathe.
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/weapons/blades.dm
  code/modules/cm_marines/equipment/gear.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
Labels: Fix

#342 Permabans now only require +BAN
  code/modules/admin/topic.dm
Labels: Administration

#301 Req Supplypacks Overhaul (Operators Operating Operationally)
  code/datums/supplypacks.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
  code/modules/projectiles/updated_projectiles/magazines/pistols.dm
Labels: Balance/Rebalance

#345 no more Methuselah marines and crewcut oppression.
  code/__DEFINES/mode.dm
  code/modules/client/preferences.dm
Labels: Tweak

#350 No more istances of marine law. (et similar policy)
  code/datums/emergency_calls/pmc.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/jobs/job/civilians.dm
  code/game/jobs/job/command.dm
  code/game/objects/items/books/manuals.dm
  code/game/objects/structures/signs.dm
Labels: Grammar and Formatting

#363 Admin Level Map Edit: Bringing Balance to the Salt
  ColonialMarinesALPHA.dme
  code/game/objects/structures/memorial.dm
  icons/obj/structures/memorial.dmi
  maps/Z.02.Admin_Level.dmm
Labels: Mapping

#295 The pyro spec no longer gets fucked by angry tackle-spam xenos dragging him into his own fire.
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
Labels: Balance/Rebalance, Test Merge Candidate

#315 Improved Item sprites for some clothes (mostly headwear).
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#337 Refactors(?) coins and tokens interaction with vendors.
  code/__DEFINES/objects.dm
  code/game/machinery/vending/marine_vending.dm
  code/game/machinery/vending/vending.dm
  code/game/machinery/vending/vending_types.dm
  code/game/objects/items/devices/coins.dm
  code/modules/cm_marines/equipment/gear.dm
  code/modules/cm_marines/smartgun_mount.dm
  nano/templates/vending_machine.tmpl
Labels: Code Improvement

#340 Fixes heart damage simply making your chest go doki doki.
  code/modules/mob/living/blood.dm
Labels: Fix

#353 Runner Drag + Queen Neuro Nerf
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Runner.dm
Labels: Balance/Rebalance

#357 Improved Revolvers/Pistols
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
  code/modules/projectiles/updated_projectiles/guns/revolvers.dm
Labels: Balance/Rebalance, Test Merge Candidate

#358 Unsuckifying the HPR
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
Labels: Balance/Rebalance, Test Merge Candidate

#176 Adds moths
  code/__DEFINES/__game.dm
  code/__DEFINES/mobs.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/gamemodes/cm_process.dm
  code/game/jobs/job/job.dm
  code/game/jobs/whitelist.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/economy/Events.dm
  code/modules/economy/Events_Mundane.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/language.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/living/carbon/human/life/handle_fire.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/human/whisper.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/mob/living/living.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/organs/limb_objects.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/names.dm
  config/alienwhitelist.txt
  config/names/moth_first.txt
  config/names/moth_last.txt
  icons/mob/human_races/r_moth.dmi
  icons/mob/species/moth/wings.dmi
  sound/voice/moth_scream.ogg
Labels: Feature

#386 Almayer Edit
  code/game/area/almayer.dm
  code/game/objects/items/reagent_containers/food/condiment.dm
  code/game/objects/structures/barsign.dm
  code/game/objects/structures/crates_lockers/closets/fitness.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
  code/modules/almayer/machinery.dm
  code/modules/cm_marines/orbital_cannon.dm
  code/modules/economy/ATM.dm
  icons/Marine/almayer_props.dmi
  icons/Marine/almayer_props64.dmi
  icons/effects/128x128.dmi
  icons/obj/machines/artillery.dmi
  icons/obj/structures/barsigns.dmi
  icons/turf/almayer.dmi
  maps/Z.03.USS_Almayer.dmm
Labels: Mapping

#336 Smartgun Improvement
  code/modules/clothing/glasses/night.dm
  code/modules/cm_marines/equipment/weapons.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/projectiles/updated_projectiles/magazines/specialist.dm
Labels: Balance/Rebalance, Test Merge Candidate

#373 Surgical Tool Fix
  code/game/objects/items/tools/surgery_tools.dm
Labels: Balance/Rebalance, Test Merge Candidate

#324 StaggerStun Proc + Shotgun Munition Rework
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Balance/Rebalance, Test Merge Candidate

#235 Defines Maths.dm : Bootleg edition
  ColonialMarinesALPHA.dme
  code/__DEFINES/_math.dm
  code/__DEFINES/maths.dm
  code/__HELPERS/game.dm
  code/__HELPERS/icons.dm
  code/__HELPERS/lists.dm
  code/__HELPERS/maths.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/click.dm
  code/controllers/_DynamicAreaLighting_TG.dm
  code/datums/diseases/advance/advance.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/gamemodes/colonialmarines/Halloween.dm
  code/game/gamemodes/colonialmarines/daedalus_prison.dm
  code/game/jobs/slot_scaling.dm
  code/game/objects/effects/effect_system/chemsmoke.dm
  code/game/objects/explosion.dm
  code/game/objects/items/devices/motion_detector.dm
  code/game/objects/items/reagent_containers/food/sandwich.dm
  code/game/objects/items/toys/cards.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/cm_marines/shuttle_backend.dm
  code/modules/economy/cash.dm
  code/modules/events/blob.dm
  code/modules/events/brand_intelligence.dm
  code/modules/maps/writer.dm
  code/modules/mining/abandonedcrates.dm
  code/modules/mining/machine_processing.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/life/handle_environment.dm
  code/modules/mob/living/carbon/human/life/handle_mutations_and_radiation.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/hostile/shyguy.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/targeting.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/surgery/surgery.dm
  code/modules/vehicles/multitile.dm
Labels: Code Improvement, Test Merge Candidate

#381 Queen Screech Rework
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
Labels: Balance/Rebalance, Test Merge Candidate

#402 Powerloader Resprite and Rework
  code/modules/vehicles/powerloader.dm
  icons/obj/powerloader.dmi
  icons/obj/vehicles.dmi
Labels: Sprites, Tweak

#408 Gives mods access to individual logs
  code/modules/admin/topic.dm
Labels: Administration
