Repository ColonialMarines-Mirror/ColonialMarines-2018, pull requests merged in 2018-08, with the labels that each got.

#68 Removes uses of the skillless pill bottle type | Fixes compilation
  code/game/objects/items/contraband.dm
  code/game/objects/items/storage/belt.dm
  code/modules/admin/verbs/select_equipment.dm
Labels: Priority: High

#100 Removes r_TRU and r_FAL
  code/__DEFINES/__game.dm
  code/__HELPERS/unsorted.dm
  code/datums/emergency_calls/colonist.dm
  code/datums/emergency_calls/zombie.dm
  code/game/gamemodes/cm_self_destruct.dm
  code/game/gamemodes/colonialmarines/colonialmarines.dm
  code/game/gamemodes/colonialmarines/huntergames.dm
  code/game/gamemodes/extended/infection.dm
  code/game/gamemodes/game_mode.dm
  code/game/machinery/bio-dome_floodlights.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/door_control.dm
  code/game/machinery/fusion_engine.dm
  code/game/machinery/groundmap_geothermal.dm
  code/game/machinery/nuclearbomb.dm
  code/game/objects/effects/effect_system/explosions.dm
  code/game/objects/items/explosives/plastique.dm
  code/game/sound.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/almayer/machinery.dm
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/cm_marines/shuttle_backend.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Crusher.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Predalien.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Embryo.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/silicon/decoy/decoy.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  code/modules/shuttles/escape_pods.dm
  code/modules/shuttles/marine_ferry.dm
  code/modules/shuttles/shuttle_ferry.dm
Labels: Code Improvement

#90 (sub)typesof
  code/WorkInProgress/Cael_Aislinn/Jungle/jungle_animals.dm
  code/WorkInProgress/Cib/MedicalSideEffects.dm
  code/WorkInProgress/computer3/test_machines.dm
  code/WorkInProgress/periodic_news.dm
  code/__DEFINES/__game.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/unsorted.dm
  code/controllers/ProcessScheduler/processScheduler.dm
  code/controllers/settings/configuration.dm
  code/controllers/voting.dm
  code/datums/datumvars.dm
  code/datums/disease.dm
  code/datums/diseases/advance/symptoms/symptoms.dm
  code/game/gamemodes/sandbox/h_sandbox.dm
  code/game/gamemodes/setupgame.dm
  code/game/jobs/access.dm
  code/game/jobs/role_authority.dm
  code/game/machinery/computer/emails.dm
  code/game/machinery/kitchen/microwave.dm
  code/game/machinery/kitchen/processor.dm
  code/game/mecha/mech_fabricator.dm
  code/game/response_team.dm
  code/game/supplyshuttle.dm
  code/modules/client/preferences_gear.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/cm_marines/Marine_Research/Marine_Research.dm
  code/modules/cm_marines/Marine_Research/Marine_Research_Console.dm
  code/modules/economy/economy_misc.dm
  code/modules/events/event_manager.dm
  code/modules/genetics/side_effects.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_stacking.dm
  code/modules/mining/minerals.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/XenoUpgrades.dm
  code/modules/mob/new_player/skill.dm
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/research/rdconsole.dm
  code/modules/research/research.dm
Labels: Code Improvement

#85 Skills
  code/__DEFINES/access.dm
  code/__DEFINES/conflict.dm
  code/__DEFINES/skills.dm
  code/datums/skills.dm
  code/game/jobs/access.dm
  code/game/jobs/job/command.dm
  code/game/machinery/autodoc.dm
  code/game/machinery/computer/computer.dm
  code/game/machinery/computer/dropship_weapons.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/groundmap_geothermal.dm
  code/game/machinery/telecomms/machine_interactions.dm
  code/game/machinery/vending/vending.dm
  code/game/machinery/vending/vending_types.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/devices/defibrillator.dm
  code/game/objects/items/explosives/plastique.dm
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/syringes.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/cm_marines/dropship_equipment.dm
  code/modules/cm_marines/equipment/mortars.dm
  code/modules/cm_marines/orbital_cannon.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/power/apc.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/shuttles/shuttle_console.dm
  code/modules/surgery/surgery.dm
  code/modules/vehicles/cm_armored.dm
  code/modules/vehicles/powerloader.dm
  code/modules/vehicles/tank.dm
Labels: Feature

#187 Makes the subtypesof() changes compile properly
  code/__DEFINES/misc.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/unsorted.dm
  code/game/jobs/access.dm
  code/game/jobs/role_authority.dm
Labels: Priority: High

#196 That's a bit shift friendo
  code/game/objects/effects/decals/Cleanable/tracks.dm
Labels: Fix

#126 Add a red bandana
  code/modules/client/preferences_gear.dm
  code/modules/clothing/head/misc.dm
  config/admins.txt
  icons/mob/head_0.dmi
  icons/obj/clothing/hats.dmi
Labels: Feature

#177 Removing a warning for survivors to not linger around the LZ
  code/game/gamemodes/cm_initialize.dm
  code/game/gamemodes/colonialmarines/Halloween.dm
  code/game/gamemodes/colonialmarines/daedalus_prison.dm
Labels: Tweak

#192 Fixes "attachments bug"
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
Labels: Fix

#142 Fixes blood tracks going beneath catwalks
  code/game/turfs/open.dm
Labels: Fix

#216 More Titles 2: Electric Boogaloo
  code/game/turfs/walls/wall_types.dm
  icons/misc/title.dmi
Labels: Tweak

#211 Grants profile access to +debug admins
  code/modules/admin/admin_ranks.dm
  code/modules/admin/holder2.dm
Labels: Administration

#206 Fix Bayonets + Faster Attachment
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
Labels: Balance/Rebalance

#89 Adds more gun/attachements options for players to use.
  code/game/machinery/vending/marine_vending.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  icons/README.txt
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
Labels: Feature, Test Merge Candidate

#237 Ports APC optimization from tg, APCs are now added to a list on creation, get_apc uses that list, this reduces locate calls and speeds get_apc up.
  code/global.dm
  code/modules/power/apc.dm
  code/modules/power/power.dm
Labels: Refactor

#219 Tanks can now break windows and window frames.
  code/modules/vehicles/cm_armored.dm
Labels: Balance/Rebalance

#250 Now you can play Gloomy Sunday at round end.
  code/game/verbs/suicide.dm
Labels: Tweak
